import { css } from '@/styled-system/css';

export const postContentStyle = css({
    '& > *': { mb: '20px' },
    '& h1': {
        fontSize: '1.9rem',
        fontWeight: '800',
        mt: '48px',
        mb: '16px',
        color: 'text.primary',
        letterSpacing: '-0.02em',
        lineHeight: '1.2',
    },
    '& h2': {
        fontSize: '1.6rem',
        fontWeight: '700',
        mt: '40px',
        mb: '14px',
        color: 'text.primary',
        letterSpacing: '-0.02em',
        lineHeight: '1.25',
    },
    '& h3': {
        fontSize: '1.3rem',
        fontWeight: '700',
        mt: '32px',
        mb: '12px',
        color: 'text.primary',
        letterSpacing: '-0.01em',
    },
    '& h4, & h5, & h6': {
        fontSize: '1.1rem',
        fontWeight: '600',
        mt: '24px',
        mb: '10px',
        color: 'text.primary',
    },
    '& p': {
        fontSize: '1.05rem',
        lineHeight: '1.8',
        color: 'text.primary',
    },
    '& ul': {
        pl: '24px',
        mb: '20px',
        listStyleType: 'disc',
    },
    '& ol': {
        pl: '24px',
        mb: '20px',
        listStyleType: 'decimal',
    },
    '& li': {
        mb: '6px',
        color: 'text.primary',
        fontSize: '1.05rem',
        lineHeight: '1.8',
    },
    '& strong, & b': {
        fontWeight: '700',
    },
    '& em, & i': {
        fontStyle: 'italic',
    },
    '& blockquote': {
        borderLeft: '3px solid token(colors.primary)',
        pl: '20px',
        fontStyle: 'italic',
        color: 'text.secondary',
        my: '28px',
        bg: 'bg.secondary',
        py: '14px',
        pr: '16px',
        borderRadius: '0 8px 8px 0',
    },
    '& pre': {
        bg: 'bg.secondary',
        p: '20px',
        borderRadius: '10px',
        overflowX: 'auto',
        fontSize: '0.875rem',
        fontFamily: 'monospace',
        my: '24px',
        border: '1px solid token(colors.border.default)',
    },
    '& code': {
        bg: 'bg.tertiary',
        px: '5px',
        py: '2px',
        borderRadius: '4px',
        fontFamily: 'monospace',
        fontSize: '0.875em',
    },
    '& pre code': {
        bg: 'transparent',
        px: 0,
        py: 0,
        borderRadius: 0,
    },
    '& a': {
        color: 'primary',
        textDecoration: 'underline',
        textUnderlineOffset: '3px',
        textDecorationThickness: '1px',
        _hover: {
            opacity: 0.8,
        },
    },
    '& img': {
        borderRadius: '10px',
        maxWidth: '100%',
        height: 'auto',
        my: '24px',
        border: '1px solid token(colors.border.default)',
    },
    '& table': {
        width: '100%',
        borderCollapse: 'collapse',
        my: '24px',
        fontSize: '0.95rem',
    },
    '& th': {
        textAlign: 'left',
        py: '10px',
        px: '14px',
        bg: 'bg.secondary',
        fontWeight: '600',
        borderBottom: '2px solid token(colors.border.default)',
        fontSize: '0.85rem',
    },
    '& td': {
        py: '10px',
        px: '14px',
        borderBottom: '1px solid token(colors.border.default)',
    },
    '& hr': {
        border: 'none',
        borderTop: '1px solid token(colors.border.default)',
        my: '40px',
    },
});
