import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import './themes.css'; // Import themes
import { css } from '@/styled-system/css';

import { Navbar } from '@/components/Navbar';
import { Sidebar } from '@/components/Sidebar';
import { AppLayout } from '@/components/AppLayout';
import { getHomeData } from '@/lib/data';
import { GlobalConfigProvider } from '@/components/providers/GlobalConfigProvider';


const inter = Inter({ subsets: ['latin'] });

export async function generateMetadata(): Promise<Metadata> {
    const homeData = getHomeData();
    const title = homeData.info?.title || 'My Portfolio';
    const description = homeData.info?.description || 'Generated by Notion as a Website';

    return {
        metadataBase: new URL(process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'),
        title: title,
        description: description,
        openGraph: {
            title: title,
            description: description,
            images: homeData.info?.og_image ? [{ url: homeData.info.og_image }] : [],
        },
    };
}

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const homeData = getHomeData();
    const showSidebar = homeData.info?.sidebar_navigation === 'true';

    const defaultTheme = homeData.info?.default_color_mode || 'light';

    return (
        <html lang="en" data-theme={defaultTheme} className={defaultTheme === 'dark' ? 'dark' : ''}>
            <head>
                {homeData.info?.favicon && <link rel="icon" href={homeData.info.favicon} sizes="any" />}
            </head>
            <body
                className={`${inter.className} ${css({ bg: 'bg.primary', color: 'text.primary' })}`}
            >
                <GlobalConfigProvider initialConfig={homeData}>
                    <AppLayout
                        sidebar={<Sidebar />}
                        navbar={<Navbar />}
                    >
                        {children}
                    </AppLayout>
                </GlobalConfigProvider>
            </body>
        </html>
    );
}
