import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { css } from '@/styled-system/css';

import { Navbar } from '@/components/Navbar';
import { Sidebar } from '@/components/Sidebar';
import { getHomeData } from '@/lib/data';


const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    metadataBase: new URL(process.env.NEXT_PUBLIC_BASE_URL || 'http://localhost:3000'),
    title: 'My Portfolio',
    description: 'Generated by Notion as a Website',
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const homeData = getHomeData();
    const showSidebar = homeData.info?.sidebar_navigation === 'true';

    const defaultTheme = homeData.info?.default_color_mode || 'light';

    return (
        <html lang="en" data-theme={defaultTheme} className={defaultTheme === 'dark' ? 'dark' : ''}>
            <head>
                {homeData.info?.favicon && <link rel="icon" href={homeData.info.favicon} sizes="any" />}
            </head>
            <body
                className={`${inter.className} ${css({ bg: 'bg.primary', color: 'text.primary' })}`}
            >
                {showSidebar ? (
                    <>
                        <Sidebar />
                        <div className={css({
                            ml: '300px', // 20px (left) + 260px (width) + 20px (gap)
                            minH: '100vh',
                            display: 'flex',
                            justifyContent: 'center', // Center content horizontally
                            width: 'calc(100% - 300px)', // Distinct width calculation
                        })}>
                            <div className={css({
                                width: '100%',
                                maxWidth: '1000px',
                                p: '40px',
                            })}>
                                {children}
                            </div>
                        </div>
                    </>
                ) : (
                    <div className={css({ maxWidth: '800px', mx: 'auto', px: '20px', pt: '80px' })}>
                        <Navbar />
                        {children}
                    </div>
                )}
                {/* DevTools removed */}
            </body>
        </html>
    );
}
